# Eureka Server Configuration
server.port=8761
spring.application.name=eureka-server

# Don't register itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Dashboard
#eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Logging
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
